apiVersion: v1
kind: Service
metadata:
  name: {{ include "task3.fullname" . }}
  labels:
    {{- include "task3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq "NodePort" .Values.service.type }}
      nodePort: 30000
      {{- end }}
  selector:
    {{- include "task3.selectorLabels" . | nindent 4 }}
